targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options passed to the generator
          explicit_to_json: true
        generate_for:
          include:
            - lib/models/*.dart